### ISSUE TITLE
Replace the current predict cache file storage with Redis

### ISSUE THREAD

**Issue by GiovanniSmokes** [apssouza22/chatflow#2]
Currently the prediciton cache is storage [in memory](https://github.com/apssouza22/chatflow/blob/main/server/src/core/agent/cache.py#L7) we should use Redis instead

**Comment by vporton** [comment]
How is prompt cache should work? Do you mean that on the same prompt we should produce the same response? It is correct? Usually AI agents have variative responses (not necessarily the same response on the same prompt).

Also, what do you mean by _Free_ Redis? Free software Redis?

**Comment by apssouza22** [comment]
@vporton I have updated the description

**Comment by vporton** [comment]
Current memory cache is limited to 30 entries. Should I also limit the number of entries in new Redis cache? (BTW, maybe you know how to limit the amount of entries in Redis?)

**Comment by vporton** [comment]
Why `PredictCache` uses base64 encoding, not simply puts strings to the cache? This seems meaningless for me.
