### ISSUE TITLE
"Something went wrong"

### ISSUE THREAD

**Issue by vporton** [apssouza22/chatflow#36]
When executing it on localhost as described by the `README.md` file, it among useful output produces errors:
![image](https://github.com/apssouza22/chatflow/assets/2900574/68ce8b35-3eef-42eb-9336-5aad73f14f6f)

**Comment by apssouza22** [comment]
What are the logs saying?

**Comment by vporton** [comment]
I will re-check this after fixing #39.

**Comment by apssouza22** [comment]
@vporton done. try again
