### ISSUE TITLE
Simplify onboarding

### ISSUE THREAD

**Issue by vporton** [apssouza22/chatflow#38]
The software asks a long series of questions for new users.

Many users would leave it in the middle. We need to make users able not to answer all these questions.

**Comment by apssouza22** [comment]
You don't need to answer those. Just click on one of the questions on the "menu"

**Comment by apssouza22** [comment]
> The software asks a long series of questions for new users.
> 
> Many users would leave it in the middle. We need to make users able not to answer all these questions.

@vporton You don't need to answer those. Just click on one of the questions on the "menu"

**Comment by apssouza22** [comment]
We want to show that those type of interactions are available

**Comment by apssouza22** [comment]
@vporton 

The first question is if you want to see the naviagiton

![Screenshot 2023-10-07 at 14 41 37](https://github.com/apssouza22/chatflow/assets/375001/ae8810be-b182-4a6a-a689-911dcc20ceb9)

**Comment by apssouza22** [comment]
@vporton Disabled it. I need to do some work before enabling it

**Comment by vporton** [comment]
Should say in the first message/question that to stop answering these questions it's enough to click into the menu. This may be not obvious for every user.
