### ISSUE TITLE
Amend docker-compose to run the app entirely

### ISSUE THREAD

**Issue by vporton** [apssouza22/chatflow#40]
Now `docker-compose.yml` uses several ports that may glitch with host software (e.g. if host runs PostgreSQL and/or Redis, they will collide). So to run it I needed to shut down my PostgreSQL, what is at least inconvenient.

I tried to fix it by adding
```
networks:
  mynetwork:
    driver: bridge
```
at the end of `docker-compose.yml` and commenting out port forwarding. But to run the app, I needed to uncomment every commented out port mappings, because the server software and the frontend are running not in Docker.

I recommend, for cleanness, to add to `docker-compose.yml` means to run all the software entirely in Docker, and to make it the recommended way to run in `README` file.

**Comment by apssouza22** [comment]
We will leave this way since we want to use the dbs inside the docker and without docker. The configuration suggested doesn't solve anything
