### ISSUE TITLE
No proper namespace for Redis keys

### ISSUE THREAD

**Issue by vporton** [apssouza22/chatflow#45]
The following demonstrates that `data_vector:9051` is available in the top-level namespace of Redis.
```
> KEYS *
...
data_vector:9051
...
> HGETALL data_vector:9051
...
```
That wrong, because on a real server Redis may be simultaneously used by other software and that key `data_vector:` is without a unique prefix.

After being tricked by the logic of existing software, I also created a subroutine that creates keys like:
```
predict_cache:Show 10 of my GitHub repos.
```
that is without a unique prefix, too.

It was created by:
```python
async def create_predict_cache():
    value_field = TextField("value")

    # Create index
    await redis_conn.ft(INDEX_NAME + "_predict_cache").create_index(
        fields=[value_field],
        definition=IndexDefinition(prefix=["predict_cache:"], index_type=IndexType.HASH)
    )
```
Here I was tricked by my intuitive understanding of API that `.ft(...)` provides a namespace `INDEX_NAME + "_predict_cache"` but this intuition contradicts to the fact that
```
HGETALL "predict_cache:Show 10 of my GitHub repos."
```
retrieves data without a unique prefix having been specified.

The next step is to understand what is the argument of `.ft()`, does it provide any useful value (because it has no expected value of providing a prefix), and then what to replace it by.

**Comment by apssouza22** [comment]
No index is required if not performing search queries. Cache only use the key to retrieve the value. No query is used therefore no index. 

The prefix `vector_search` is enough to avoid colision with other apps that might be sharing the same instace
